// <auto-generated />
using System;
using LearningTask1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningTask1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearningTask1.Models.BusinessCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusinessCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            DOB = new DateOnly(1990, 1, 1),
                            Email = "john@example.com",
                            Gender = "Male",
                            Name = "John Doe",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ave",
                            DOB = new DateOnly(1992, 5, 10),
                            Email = "jane@example.com",
                            Gender = "Female",
                            Name = "Jane Smith",
                            PhoneNumber = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine Rd",
                            DOB = new DateOnly(1985, 3, 15),
                            Email = "michael@example.com",
                            Gender = "Male",
                            Name = "Michael Brown",
                            PhoneNumber = "1112223333"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Cedar Ln",
                            DOB = new DateOnly(1995, 7, 22),
                            Email = "emily@example.com",
                            Gender = "Female",
                            Name = "Emily White",
                            PhoneNumber = "4445556666"
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Maple St",
                            DOB = new DateOnly(1988, 11, 30),
                            Email = "david@example.com",
                            Gender = "Male",
                            Name = "David Green",
                            PhoneNumber = "7778889999"
                        },
                        new
                        {
                            Id = 6,
                            Address = "987 Birch Ave",
                            DOB = new DateOnly(1993, 2, 5),
                            Email = "sophia@example.com",
                            Gender = "Female",
                            Name = "Sophia Blue",
                            PhoneNumber = "2223334444"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
